// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfbrnV1ouUXxpKm-JfV5-LWu8I3Fl7drI',
    appId: '1:197022001798:web:f8921341720e5a5d0c3f07',
    messagingSenderId: '197022001798',
    projectId: 'live-talk07',
    authDomain: 'live-talk07.firebaseapp.com',
    storageBucket: 'live-talk07.firebasestorage.app',
    measurementId: 'G-QN2PENFHY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY3hPmOs-G6EP9sqo7KeiK8l_OAanRlbg',
    appId: '1:197022001798:android:c5002fbea66f72fc0c3f07',
    messagingSenderId: '197022001798',
    projectId: 'live-talk07',
    storageBucket: 'live-talk07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4KHZ0CnaLVQM6jKU_9MEAZcKb03SzbRM',
    appId: '1:197022001798:ios:eb611b9b8f33207f0c3f07',
    messagingSenderId: '197022001798',
    projectId: 'live-talk07',
    storageBucket: 'live-talk07.firebasestorage.app',
    iosBundleId: 'com.example.rtcLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4KHZ0CnaLVQM6jKU_9MEAZcKb03SzbRM',
    appId: '1:197022001798:ios:eb611b9b8f33207f0c3f07',
    messagingSenderId: '197022001798',
    projectId: 'live-talk07',
    storageBucket: 'live-talk07.firebasestorage.app',
    iosBundleId: 'com.example.rtcLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfbrnV1ouUXxpKm-JfV5-LWu8I3Fl7drI',
    appId: '1:197022001798:web:fc016f9eb77053820c3f07',
    messagingSenderId: '197022001798',
    projectId: 'live-talk07',
    authDomain: 'live-talk07.firebaseapp.com',
    storageBucket: 'live-talk07.firebasestorage.app',
    measurementId: 'G-HHXZQ7T18H',
  );
}
